site_name: Symbio Documentation
repo_url: https://github.com/ploetz-zeller/symbio-documentation
copyright: Ploetz + Zeller GmbH

theme:
  name: 'material'
  favicon: 'assets/images/favicon.ico'
  logo: 'assets/images/logo.png'
  font: false
  palette:
    primary: 'blue'
  feature:
    tabs: true

extra_css:
  - 'assets/stylesheets/extra.css'

markdown_extensions:
  - admonition
  - codehilite
  - markdown_include.include:
      base_path: docs

nav:
  - Admin:
    - Introduction: admin/index.md
    - Installation Guide:
      - Installation:
        - Preparation: admin/installation-guide/installation/Requirements.md
        - Scripted Installation: admin/installation-guide/installation/Installation-Skripted.md
        - Manual Installation: admin/installation-guide/installation/Installation-Manual.md
        - First Steps: admin/installation-guide/installation/Finishing.md
      - Configuration with SAML:
        - Introduction: admin/installation-guide/saml-configuration/1_introduction.md
        - Setting Up SAML: admin/installation-guide/saml-configuration/2_setting-up-saml.md
        - User & Rights Management: admin/installation-guide/saml-configuration/3_user-rights-management.md
        - Example - Symbio & AD FS: admin/installation-guide/saml-configuration/4_example-adfs.md
        - Example - Symbio & Azure AD: admin/installation-guide/saml-configuration/5_example-aad.md
        - Checklist: admin/installation-guide/saml-configuration/6_checklist.md
      - Symbio Apps Authentication:
        - Azure AD: admin/installation-guide/symbio-apps-auth/azure-ad.md
        - OneLogin: admin/installation-guide/symbio-apps-auth/onelogin.md
      - OAuth Configuration:
        - Setting Up OAuth: admin/installation-guide/oauth-configuration/setting-up-oauth.md
    - Services:
      - Introduction: admin/services/introduction/introduction.md
      - Atlassian Connector:
        - Administration guide: admin/services/atlassian-connector/administration_guide.md
        - Using Symbio to Atlassian: admin/services/atlassian-connector/using_symbioatlassian.md
      - Celonis Importer:
        - Installation manual: admin/services/celonis-importer/install-service-manual.md
        - Configuration: admin/services/celonis-importer/configuration.md
        - Usage: admin/services/celonis-importer/usage.md
      - Import of vsdx files: admin/services/import-of-vsdx-files/import-of-vsdx-files.md
      - Intrafind Indexer:
        - Introduction: admin/services/intrafind-indexer/index.md
        - Installation: admin/services/intrafind-indexer/installation.md
        - Configuration: admin/services/intrafind-indexer/configuration.md
        - Console Application: admin/services/intrafind-indexer/consoleapplication.md
        - About Logging: admin/services/intrafind-indexer/logging.md
      - Intrafind Search Proxy:
        - Installation: admin/services/intrafind-search-proxy/installation.md
        - Configuration: admin/services/intrafind-search-proxy/configuration.md
      - Process Portal Exporter:
        - Installation manual: admin/services/process-portal-exporter/install-service-manual.md
        - Configuration: admin/services/process-portal-exporter/configuration.md
        - Usage: admin/services/process-portal-exporter/usage.md
      - Reporting Service:
        - Overview: 
          - Introduction: admin/services/reporting-service/overview.md
          - Authentication Token IsPermittedEverywhere: developer/is-permitted-everywhere.md
        - Installation:
          - SSRS & Reports: admin/services/reporting-service/deploy-ssrs.md
          - Connector Web Service & Console Application: admin/services/reporting-service/deploy-connector-console.md
        - Configuration:
          - Connector Web Service & Console Application: admin/services/reporting-service/config-connector-console.md
          - Symbio Report Pool & Symbio Reporting:  admin/services/reporting-service/config-symbio.md
        - Operation: admin/services/reporting-service/operation.md
      - SAP Solution Manager Connector:
        - Introduction: 
          - Overview: admin/services/sap-solution-manager-connector/Introduction_Overview.md
          - Basic HowTo: admin/services/sap-solution-manager-connector/Introduction_BasicHowTo.md
          - Recommended usage: admin/services/sap-solution-manager-connector/Introduction_RecommendedUse.md
          - Limitations: admin/services/sap-solution-manager-connector/Introduction_Limitations.md
        - Installation:
          - Service installation: admin/services/sap-solution-manager-connector/Installation_ServiceInstallation.md
          - Configuration: admin/services/sap-solution-manager-connector/Installation_Configuration.md
          - Versioning: admin/services/sap-solution-manager-connector/Installation_Versioning.md
        - SAP Solution Manager to Symbio synchronization:
          - Process structure synchronization: admin/services/sap-solution-manager-connector/SolManToSymbio_ProcessSync.md
          - Library objects synchronization: admin/services/sap-solution-manager-connector/SolManToSymbio_LibraryObjectsSync.md
        - Symbio to SAP Solution Manager synchronization:
          - Process structure synchronization: admin/services/sap-solution-manager-connector/SymbioToSolMan_ProcessSync.md
          - Diagram synchronization: admin/services/sap-solution-manager-connector/SymbioToSolMan_DiagramSync.md
          - Subprocess diagram element synchronization: admin/services/sap-solution-manager-connector/SymbioToSolMan_SubProcessDiagramElementSync.md
        - Document Synchronization: admin/services/sap-solution-manager-connector/DocumentSynchronization.md
        - Task Consolidation: admin/services/sap-solution-manager-connector/TaskReferenceConsolidation.md
        - For developers:
          - SAP Solution Manager to Symbio mapping: admin/services/sap-solution-manager-connector/Symbio_SolutionManager_StructureMapping.md
          - SAP Solution Manager API explained: admin/services/sap-solution-manager-connector/SolutionManagerAPIExplained.md
          - SAP Solution Manager microservice architecture: admin/services/sap-solution-manager-connector/SolManConnectorArchitecture.md
      - SVG To Image Converter:
        - Installation:
            - Scripted Installation: admin/services/rendering-service/installation-scripted.md
            - Manual installation: admin/services/rendering-service/installation-manual.md
            - Verification: admin/services/rendering-service/verification.md
            - Troubleshooting: admin/services/rendering-service/troubleshooting.md
        - Deinstallation: admin/services/rendering-service/deinstallation-manual.md
      - Unique ID Provider:
        - Installation:
          - Intro: admin/services/unique-id-provider/install-intro.md
          - General conditions: admin/services/unique-id-provider/install-conditions.md
          - Scripted installation: admin/services/unique-id-provider/install-scripted.md
          - Manual installation: admin/services/unique-id-provider/install-manual.md
          - Create token: admin/services/unique-id-provider/install-create-token.md
          - Gotchas: admin/services/unique-id-provider/install-gotchas.md
        - Configuration:
          - Before Start: admin/services/unique-id-provider/config-before-start.md
          - Create ID Provider: admin/services/unique-id-provider/config-create-provider.md
          - Create ID Configuration: admin/services/unique-id-provider/config-provider-config.md
        - Manual: admin/services/unique-id-provider/manual-how-to-use.md
      - Web Jobs Scheduler: admin/services/web-jobs-scheduler.md
    - Administration:
      - Getting Started:
        - Introduction: admin/administration/introduction.md
        - Database Pools: admin/administration/database-pools.md
        - Storage collections and databases: admin/administration/storage-collections-and-databases.md
      - Home site:
        - Configuration: admin/administration/home-site/home-site.md
      - User Management:
        - Users and user groups: admin/administration/user-management/users.md
      - Permissions:
        - Introduction: admin/administration/permissions/permissions.md
        - Permission levels explained: admin/administration/permissions/permission-levels-explained.md
        - Creating and assigning permission sets: admin/administration/permissions/create-assign-permissionsets.md
        - Permissions for facets feature: admin/administration/permissions/facet-permission-feature.md
        - Permissions for objects made more flexible: admin/administration/permissions/permissions-maintenance-extension.md
      - Storage configuration:
        - Settings: admin/administration/storage-settings/storage-settings.md
        - Services: admin/administration/storage-services/storage-services.md
        - Configuration: admin/administration/storage-configuration/storage-configuration.md
      - Data Management:
        - Introduction: admin/administration/data-management/data-management.md
        - Importer: admin/administration/data-management/importer.md
      - External Systems:
        - Creating external systems: admin/administration/external-systems/creating-external-systems.md
        - Connect external systems: admin/administration/external-systems/connect-external-systems.md
        - Disconnect external systems: admin/administration/external-systems/disconnect-external-systems.md
        - Create token and inform external systems: admin/administration/external-systems/create-token-and-inform-external-systems.md
        - Authentication Token IsPermittedEverywhere: developer/is-permitted-everywhere.md
      - Fact Sheets:
        - Creating fact sheets: admin/administration/fact-sheets/creating-factsheets.md
        - Use fact sheets: admin/administration/fact-sheets/use-factsheets.md
        - Fact sheet - Related global objects: admin/administration/fact-sheets/factsheet-global-objects.md
      - Stereotypes:
        - Creating stereotypes: admin/administration/stereotypes/creating-stereotypes.md
        - Use stereotypes: admin/administration/stereotypes/use-stereotypes.md
    - Features:
      - Introduction: admin/features/introduction/introduction.md
      - General design:
        - Authentication Provider OAuth: admin/features/general-design/authentication-provider/autentication-provider.md
        - Deactivate architecture in system facet: admin/features/general-design/deactivate_architecture-systems/deactivate-architecture-systems.md
        - Permissions for architectures: admin/features/general-design/permissions-architectures/permissions-architectures.md
        - Permissions for facets: admin/features/general-design/facet-permissions/facet-permissions.md
        - Permissions for objects made more flexible: admin/features/general-design/permissions-more-flexible/permissions-more-flexible.md
        - Permissions get copied from comparable user instead of recalculated: admin/features/general-design/permissions-copied/permissions-copied.md
        - Document digitalization: admin/features/general-design/document-digitalization/document-digitalization.md
        - Document digitalization on all facets: admin/features/general-design/document-digitalization-on-all-facets/document-digitalization-all-facets.md
        - Favorite management Grouping favorites: admin/features/general-design/group-management-for-favorites/group-management-for-favorites.md
        - Favorite management Sharing favorites: admin/features/general-design/group-management-for-favorites-sharing/group-management-for-favorites-sharing.md
        - Multiselect list feature: admin/features/general-design/multiselect-list-feature/multiselect-list-feature.md
        - User filters: admin/features/general-design/user-filters/user-filters.md
        - Subscriptions for categories: admin/features/general-design/subscriptions-for-categories/subscriptions-for-categories.md
      - Process design:
        - Activate exclusive process editing: admin/features/process-design/activate-exclusive-process-editing/activate-exclusive-process-editing.md
        - Best practice tasks: admin/features/process-design/best-practice-tasks/best-practice-tasks.md
        - BPMN Icons shown on process flow objects: admin/features/process-design/bpmn2.0-icons/bpmn-icons.md
        - Method - Changed evaluation groups for processes: admin/features/process-design/changed-evaluation-groups-processes/changed-evaluation-groups-processes.md
        - Copy and move shapes: admin/features/process-design/copy-move-shapes/copy-and-move-shapes.md
        - Enhancement of detailed modeling: admin/features/process-design/enhancement-detailed-modeling/enhancement-of-detailed-modeling.md
        - Fact sheet - Related global objects: admin/features/process-design/fact_sheet_related-global-objects/fact-sheet_related-global-objects.md
        - Graphical version comparison: admin/features/process-design/graphical_comparison/graphical-comparison.md
        - RACI instead of RASCI: admin/features/process-design/raci_instead_rasci/raci-instead-of-rasci.md
        - Swimlane for Applications: admin/features/process-design/swimlane-for-applications/swimlane-for-applications.md
      - Repository design:
        - ArchiMate Conversions: admin/features/repository-design/archimate-conversions/archimate-conversions.md
        - Classification of information: admin/features/repository-design/classification-of-info/classification-of-information.md
        - Method - Maintain Measures status: admin/features/repository-design/measure-status/measure-status.md
        - Skill Feature: admin/features/repository-design/skill-feature/skill-feature.md
        - Method - Requirements for Main Processes: admin/features/repository-design/requirements-main-processes/requirements-main-processes.md
  - Developer:
    - Introduction: developer/index.md
    - Getting Started: developer/getting-started.md
    - REST API:
      - How To:
        - Authentication Tokens: developer/rest-api/how-to/rest-symbio-auth-token-client-temp-example-documentation/rest-symbio-auth-token-client-temp-example-documentation.md
        - Authentication Token IsPermittedEverywhere: developer/is-permitted-everywhere.md
        - How to get all released mainprocesses: developer/rest-api/how-to/quickstart-mainprocesses/quickstart-mainprocesses.md
        - Filter: developer/rest-api/how-to/filter.md
        - Errors: developer/rest-api/how-to/error.md
        - Symbio REST using Powershell: developer/rest-api/how-to/powershell/rest-using-powershell.md
        - Using Javascript: developer/rest-api/how-to/javascript/index.md
      - Reference:
        - Storage Information: developer/rest-api/reference/storage-info.md
        - Facets: 
            - 1.0: developer/rest-api/reference/facets.md
            - 4.0: developer/rest-api/reference/facets-4.md
        - Views: 
            - 1.0: developer/rest-api/reference/views.md
            - 4.0: developer/rest-api/reference/views-4.md
        - Configuration: developer/rest-api/reference/config.md
        - Permission sets: developer/rest-api/reference/permission-sets.md
        - Reporting: developer/rest-api/reference/reporting.md
        - Versioning: developer/rest-api/reference/versioning.md
        - Elements:
          - List: developer/rest-api/reference/elements-list.md
          - Get: developer/rest-api/reference/elements-get.md
          - Update: developer/rest-api/reference/elements-update.md
          - Delete: developer/rest-api/reference/elements-delete.md
        - Attributes:
          - List: developer/rest-api/reference/attributes-list.md
          - Get: developer/rest-api/reference/attributes-get.md
        - Related:
          - List: developer/rest-api/reference/related-list.md
          - Get: developer/rest-api/reference/related-get.md
          - Children: developer/rest-api/reference/related-children.md
          - Element Information: developer/rest-api/reference/elementsinfo-get.md
        - Content:
          - Get: developer/rest-api/reference/content.md
          - Create: developer/rest-api/reference/content-create.md
        - Transitions:
          - InProcess transitions: developer/rest-api/reference/transitions-inprocess.md
          - Release transitions: developer/rest-api/reference/transitions-release.md
        - Release:
          - Create Version: developer/rest-api/reference/release-create-version.md
          - Change State: developer/rest-api/reference/release-change-state.md
        - Graphic:
          - Get: developer/rest-api/reference/graphic-get.md
        - Maintain: 
          - Get: developer/rest-api/reference/maintain.md
    - Services:
      - External Systems: developer/services/external-systems.md
      - External System Types: developer/services/external-system-types.md
  - Azure:
    - Introduction: azure/index.md
    - Runbooks: azure/runbooks.md
    - Infrastructure as code:
      - Introduction: azure/infrastructure-as-code/introduction.md
      - Azure resources: azure/infrastructure-as-code/azure-resources.md
      - Azure resource templates: azure/infrastructure-as-code/azure-resource-templates.md
      - Azure IaC Deployments: azure/infrastructure-as-code/azure-deployments.md
      - Creating a project in Visual Studio: azure/infrastructure-as-code/creating-vs-project.md
